env:
  browser: true
  es2021: true
  node: true
extends:
  - google
  - 'plugin:vue/essential'
  - '@nuxtjs/eslint-config-typescript'
  - eslint:recommended
  - prettier
  - prettier/prettier
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-unused-vars': off
  no-unused-vars: off # This is needed to define vars in Vue Typescript and used in Vue template

  indent: ["error", 2, { "ArrayExpression": 1, "MemberExpression": 2 }]
  semi: ["error", "always"]
  quotes: ["warn", "single"]
  # Th following section of rules are specific to this Project
  comma-dangle: off
  guard-for-in: off
  no-console: off
  vue/attribute-hyphenation: off

  # Buggy / not working rules
  no-invalid-this: off # This Eslint rule doesn't work well with Vue
  vue/no-unused-components: off

  ## TO remove
  import/named: off
  require-jsdoc: off
  valid-jsdoc: off

  ## The following rules are temp disabled before we fully enforce.

  # The following rules are deprecated in ESLint v7.0.0
  node/handle-callback-err: off
  node/no-new-require: off
  node/no-path-concat: off
ignorePatterns: ["docs"]