version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.19.1
    steps:
      - checkout:
          path: "~/repo"
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run jest small tests
          command: yarn test:small
      - run:
          name: Run jest full tests with report
          command: yarn test:report
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/results.xml"
      - store_test_results:
          path: reports/jest
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage
  chromatic-deployment: 
    docker:
      - image: circleci/node:12.19.1
    working_directory: ~/repo
    steps:
      - checkout:
          path: "~/repo"
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
  chromatic-deploy:
    jobs:
      - chromatic-deployment # 👈 Runs the Chromatic job implemented above